### ISSUE TITLE
cant run caffeine

### ISSUE THREAD

**Issue by seniorkiller** [caffeine-ng/caffeine-ng#106]
it used to be working but after a while not using it i cant run it
im not sure if im doing anything that broke it but when i run it on terminal it show this
```
/usr/lib/python3.10/site-packages/caffeine/main.py:61: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3
Traceback (most recent call last):
  File "/usr/bin/caffeine", line 33, in <module>
    sys.exit(load_entry_point('caffeine-ng==3.5.1', 'gui_scripts', 'caffeine')())
  File "/usr/lib/python3.10/site-packages/caffeine/main.py", line 454, in main
    main = GUI(arguments["--preferences"])
  File "/usr/lib/python3.10/site-packages/caffeine/main.py", line 155, in __init__
    self.__core = Caffeine(self.__process_manager)
  File "/usr/lib/python3.10/site-packages/caffeine/core.py", line 82, in __init__
    self._ewmh = EWMH()
  File "/usr/lib/python3.10/site-packages/ewmh/ewmh.py", line 70, in __init__
    self.display = _display or display.Display()
  File "/usr/lib/python3.10/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python3.10/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/lib/python3.10/site-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Invalid MIT-MAGIC-COOKIE-1 key' 
```

**Comment by seniorkiller** [comment]
for some reason it work again
