### ISSUE TITLE
Provide support for AyatanaAppIndicator3

### ISSUE THREAD

**Issue by maxerbox** [caffeine-ng/caffeine-ng#114]
Hello,

Debian based distros are not using libappindicator anymore.
Please use AyatanaAppIndicator3-0.1 instead https://lazka.github.io/pgi-docs/AyatanaAppIndicator3-0.1/ as a fallback.
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037

```
Traceback (most recent call last):
  File "/usr/local/bin/caffeine", line 11, in <module>
    load_entry_point('caffeine-ng==3.5.1.post88+gef22619', 'gui_scripts', 'caffeine')()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/site-packages/caffeine_ng-3.5.1.post88+gef22619-py3.7.egg/caffeine/cli.py", line 9, in <module>
    from caffeine.main import GUI
  File "/usr/local/lib/python3.7/site-packages/caffeine_ng-3.5.1.post88+gef22619-py3.7.egg/caffeine/main.py", line 29, in <module>
    gi.require_version("AppIndicator3", "0.1")
  File "/usr/local/lib/python3.7/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
``

**Comment by WhyNotHugo** [comment]
Last commit for libappindicator seems to have been over two years ago: https://code.launchpad.net/libappindicator

So switching to a currently maintained alternative as suggested here is a valid issue.

However, libayatana-appindicator does not provide Python bindings, so it doesn't seem like the correct alternative: https://github.com/AyatanaIndicators/libayatana-appindicator/issues/58

**Comment by WhyNotHugo** [comment]
This project has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/114
