### ISSUE TITLE
Caffeine-ng-git not showing in status bar on KDE

### ISSUE THREAD

**Issue by guilhermeaugusto9** [caffeine-ng/caffeine-ng#54]
Hello,

I install caffeine-ng-git from yay in Arch Linux (using EndeavourOS with KDE) , yesterday caffeine was running fine, but since today, is not showing in the status bar, and the command ./bin/caffeine doesnt work either.

Does somebody know what I can make to fix it? 

I already uninstall and reinstall

follows my system information and the print of status bar:

ps. when I just click in the icon dont happen anything

![2021-02-26_22-10](https://user-images.githubusercontent.com/23098357/109370570-a3401e00-787f-11eb-99cb-5c4ae2131790.png)
![2021-02-26_22-11_1](https://user-images.githubusercontent.com/23098357/109370575-a63b0e80-787f-11eb-9e44-72d7381d85ae.png)
![2021-02-26_22-11](https://user-images.githubusercontent.com/23098357/109370578-a935ff00-787f-11eb-869e-7e3fa94a285d.png)

**Comment by SamuelLeeD** [comment]
I'm on Manjaro with much the same problem. This is what I get when running `caffeine` in the terminal:

```/usr/lib/python3.9/site-packages/caffeine/main.py:61: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
from gi.repository import AppIndicator3
INFO:caffeine.core:Caffeine is starting up...
(caffeine:10901): Gtk-WARNING **: 15:28:52.979: Could not find the icon 'caffeine'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
http://icon-theme.freedesktop.org/releases
Traceback (most recent call last):
File "/usr/bin/caffeine", line 33, in <module>
sys.exit(load_entry_point('caffeine-ng==3.5.1', 'gui_scripts', 'caffeine')())
File "/usr/lib/python3.9/site-packages/caffeine/main.py", line 454, in main
main = GUI(arguments["--preferences"])
File "/usr/lib/python3.9/site-packages/caffeine/main.py", line 251, in __init__
get_icon_pixbuf(16),
File "/usr/lib/python3.9/site-packages/caffeine/icons.py", line 48, in get_icon_pixbuf
pixbuf = icon_theme.load_icon(icon_name, size, Gtk.IconLookupFlags.NO_SVG)
gi.repository.GLib.Error: gtk-icon-theme-error-quark: Icon 'caffeine' not present in theme (null) (0)```

I do have `hicolor-icon-theme` installed. This problem only appears with 3.5.1; when I downgrade to 3.4.2 everything works (so that's what I'm using right now)

**Comment by WhyNotHugo** [comment]
How are you installing caffeine? What's the output of `find /usr/share -iname "*caffeine*"`?

**Comment by SamuelLeeD** [comment]
I installed `caffeine-ng` from the AUR. The output is:
```
/usr/share/icons/ubuntu-mono-dark/status/scalable/caffeine-cup-full.svg
/usr/share/icons/ubuntu-mono-dark/status/scalable/caffeine-cup-empty.svg
/usr/share/icons/ubuntu-mono-dark/status/48/caffeine-cup-empty.png
/usr/share/icons/ubuntu-mono-dark/status/48/caffeine-cup-full.png
/usr/share/icons/ubuntu-mono-dark/status/16/caffeine-cup-empty.png
/usr/share/icons/ubuntu-mono-dark/status/16/caffeine-cup-full.png
/usr/share/icons/ubuntu-mono-dark/status/22/caffeine-cup-empty.png
/usr/share/icons/ubuntu-mono-dark/status/22/caffeine-cup-full.png
/usr/share/icons/ubuntu-mono-dark/status/32/caffeine-cup-empty.png
/usr/share/icons/ubuntu-mono-dark/status/32/caffeine-cup-full.png
/usr/share/icons/ubuntu-mono-dark/status/24/caffeine-cup-empty.png
/usr/share/icons/ubuntu-mono-dark/status/24/caffeine-cup-full.png
/usr/share/icons/hicolor/16x16/apps/caffeine.png
/usr/share/icons/hicolor/16x16/status/caffeine-cup-empty.png
/usr/share/icons/hicolor/16x16/status/caffeine-cup-full.png
/usr/share/icons/hicolor/48x48/apps/caffeine.png
/usr/share/icons/hicolor/48x48/status/caffeine-cup-empty.png
/usr/share/icons/hicolor/48x48/status/caffeine-cup-full.png
/usr/share/icons/hicolor/32x32/apps/caffeine.png
/usr/share/icons/hicolor/32x32/status/caffeine-cup-empty.png
/usr/share/icons/hicolor/32x32/status/caffeine-cup-full.png
/usr/share/icons/hicolor/scalable/apps/caffeine.svg
/usr/share/icons/hicolor/scalable/status/caffeine-cup-full.svg
/usr/share/icons/hicolor/scalable/status/caffeine-cup-empty.svg
/usr/share/icons/hicolor/22x22/apps/caffeine.png
/usr/share/icons/hicolor/22x22/status/caffeine-cup-empty.png
/usr/share/icons/hicolor/22x22/status/caffeine-cup-full.png
/usr/share/icons/hicolor/24x24/apps/caffeine.png
/usr/share/icons/hicolor/24x24/status/caffeine-cup-empty.png
/usr/share/icons/hicolor/24x24/status/caffeine-cup-full.png
/usr/share/glib-2.0/schemas/net.launchpad.caffeine.gschema.xml
/usr/share/applications/caffeine-preferences.desktop
/usr/share/applications/caffeine.desktop
/usr/share/pixmaps/caffeine.png
find: ‘/usr/share/polkit-1/rules.d’: Permission denied
find: ‘/usr/share/hplip/base/__pycache__’: Permission denied
/usr/share/man/man1/caffeine.1.gz
```

I had been using version 3.4.2 of the AUR package, but I've just seen that Manjaro has a new version 3.5.1-1.2 on the official Manjaro repository (also called `caffeine-ng`), whereas the AUR one is on version 3.5.1-1. The one on the official Manjaro repository works fine (though I could have sworn it wasn't there before; I had been trying to fix this for quite some time and I only remember seeing the AUR version).

**Comment by SamuelLeeD** [comment]
I installed `caffeine-ng` from the AUR. Going back to version 3.5.1-1, the output is:
```
/usr/share/icons/ubuntu-mono-dark/status/scalable/caffeine-cup-full.svg
/usr/share/icons/ubuntu-mono-dark/status/scalable/caffeine-cup-empty.svg
/usr/share/icons/ubuntu-mono-dark/status/48/caffeine-cup-empty.png
/usr/share/icons/ubuntu-mono-dark/status/48/caffeine-cup-full.png
/usr/share/icons/ubuntu-mono-dark/status/16/caffeine-cup-empty.png
/usr/share/icons/ubuntu-mono-dark/status/16/caffeine-cup-full.png
/usr/share/icons/ubuntu-mono-dark/status/22/caffeine-cup-empty.png
/usr/share/icons/ubuntu-mono-dark/status/22/caffeine-cup-full.png
/usr/share/icons/ubuntu-mono-dark/status/32/caffeine-cup-empty.png
/usr/share/icons/ubuntu-mono-dark/status/32/caffeine-cup-full.png
/usr/share/icons/ubuntu-mono-dark/status/24/caffeine-cup-empty.png
/usr/share/icons/ubuntu-mono-dark/status/24/caffeine-cup-full.png
/usr/share/icons/hicolor/16x16/apps/caffeine.png
/usr/share/icons/hicolor/16x16/status/caffeine-cup-empty.png
/usr/share/icons/hicolor/16x16/status/caffeine-cup-full.png
/usr/share/icons/hicolor/48x48/apps/caffeine.png
/usr/share/icons/hicolor/48x48/status/caffeine-cup-empty.png
/usr/share/icons/hicolor/48x48/status/caffeine-cup-full.png
/usr/share/icons/hicolor/32x32/apps/caffeine.png
/usr/share/icons/hicolor/32x32/status/caffeine-cup-empty.png
/usr/share/icons/hicolor/32x32/status/caffeine-cup-full.png
/usr/share/icons/hicolor/scalable/apps/caffeine.svg
/usr/share/icons/hicolor/scalable/status/caffeine-cup-full.svg
/usr/share/icons/hicolor/scalable/status/caffeine-cup-empty.svg
/usr/share/icons/hicolor/22x22/apps/caffeine.png
/usr/share/icons/hicolor/22x22/status/caffeine-cup-empty.png
/usr/share/icons/hicolor/22x22/status/caffeine-cup-full.png
/usr/share/icons/hicolor/24x24/apps/caffeine.png
/usr/share/icons/hicolor/24x24/status/caffeine-cup-empty.png
/usr/share/icons/hicolor/24x24/status/caffeine-cup-full.png
/usr/share/glib-2.0/schemas/net.launchpad.caffeine.gschema.xml
/usr/share/applications/caffeine-preferences.desktop
/usr/share/applications/caffeine.desktop
/usr/share/pixmaps/caffeine.png
find: ‘/usr/share/polkit-1/rules.d’: Permission denied
find: ‘/usr/share/hplip/base/__pycache__’: Permission denied
/usr/share/man/man1/caffeine.1.gz
```

**Comment by guilhermeaugusto9** [comment]
I have installed using yay -S caffeine-ng, and the problemn not solve here :(

**Comment by plum** [comment]
I also have the sam eproblem , since an update of caffine. It was fine before. Tried re-installing to no avail.

WQhen Starting form the cpommandline, I get the notoification, 'caffeine is running, to show the tray icon run caffeine -p'

However caffeine-ng has no such option -p

**Comment by WhyNotHugo** [comment]
This project has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/54
