### ISSUE TITLE
uninhibition seemingly has no effect

### ISSUE THREAD

**Issue by VoodaGod** [caffeine-ng/caffeine-ng#61]
on current master since #56 and #58, once caffeine has inhibited, uninhibiting seems to have no effect.
```
caffeine --verbose start                             
DEBUG:caffeine.cli:Running with --verbose.
INFO:caffeine.core:Running with triggers: [<caffeine.triggers.ManualTrigger object at 0x7f8581acf730>, WhiteListTrigger(process_manager=<caffeine.procmanager.ProcManager object at 0x7f8582e03430>), <caffeine.triggers.FullscreenTrigger object at 0x7f8581acf790>, <caffeine.triggers.PulseAudioTrigger object at 0x7f8581acf3d0>].
INFO:caffeine.core:Caffeine is starting up...
INFO:caffeine.core:Desired state is: DesiredState.UNINHIBITED
INFO:caffeine.core:XdgPowerManagmentInhibitor is applicable, state: False
INFO:caffeine.core:XorgInhibitor is applicable, state: False
INFO:caffeine.core:XdgScreenSaverInhibitor is applicable, state: False
INFO:caffeine.core:DpmsInhibitor is applicable, state: False
DEBUG:caffeine.triggers:Video playback detected (no name, scream, spotify, pulseeffects).
DEBUG:caffeine.core:<caffeine.triggers.PulseAudioTrigger object at 0x7f8581acf3d0> requested DesiredState.INHIBIT_ALL.
INFO:caffeine.core:Desired state is: DesiredState.INHIBIT_ALL
INFO:caffeine.core:XdgPowerManagmentInhibitor is applicable, state: True
INFO:caffeine.core:XorgInhibitor is applicable, state: True
INFO:caffeine.core:XdgScreenSaverInhibitor is applicable, state: True
INFO:caffeine.core:DpmsInhibitor is applicable, state: True
INFO:caffeine.core:Desired state is: DesiredState.UNINHIBITED
INFO:caffeine.core:XdgPowerManagmentInhibitor is applicable, state: False
INFO:caffeine.core:XorgInhibitor is applicable, state: False
INFO:caffeine.core:XdgScreenSaverInhibitor is applicable, state: False
INFO:caffeine.core:DpmsInhibitor is applicable, state: False
```
Once caffeine has inhibited, my system refuses to go to sleep or enter the lock screen, even when caffeine claims to no longer be inhibiting, as long as caffeine is running. This is as far as i have seen also unrelated to the trigger that caused inhibition
My system: Manjaro @ 5.10 with KDE Plasma 5.21
Can anyone else reproduce this?
Haven't found any promising leads yet on what change could have caused this in those PRs :( will continue to investigate

**Comment by carlocastoldi** [comment]
I have the same problem. Both with `v3.5.1` and the git version.

This is my output:
```
/usr/lib/python3.9/site-packages/caffeine/main.py:61: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3
INFO:caffeine.core:Caffeine is starting up...
INFO:caffeine.core:Audio playback detected (spotify). Inhibiting.
INFO:caffeine.core:GnomeInhibitor is applicable, state: True
INFO:caffeine.core:XorgInhibitor is applicable, state: True
INFO:caffeine.core:XdgScreenSaverInhibitor is applicable, state: False
server does not have extension for +dpms option
INFO:caffeine.core:DpmsInhibitor is applicable, state: False
INFO:caffeine.core:
```

`server does not have extension for +dpms option` is spammed in the console and `journalctl` with the git version.
Additionally the last time the system suspended I could no longer access my pc neither in GUI nor in tty.
I am not sure if caffeine is related to it, but the following is the last output of `caffeine` i have in `journalctl` during the suspension of my pc:
```
apr 01 13:30:38 thinkpad-t480 caffeine.desktop[39135]: server does not have extension for -dpms option
apr 01 13:30:48 thinkpad-t480 caffeine.desktop[39184]: server does not have extension for +dpms option
apr 01 13:30:58 thinkpad-t480 caffeine.desktop[30468]: Traceback (most recent call last):
apr 01 13:30:58 thinkpad-t480 caffeine.desktop[30468]:   File "/usr/lib/python3.9/site-packages/caffeine/core.py", line 131, in run_all_triggers
apr 01 13:30:58 thinkpad-t480 caffeine.desktop[30468]:     self.apply_desired_status(show_notification)
apr 01 13:30:58 thinkpad-t480 caffeine.desktop[30468]:   File "/usr/lib/python3.9/site-packages/caffeine/core.py", line 271, in apply_desired_status
apr 01 13:30:58 thinkpad-t480 caffeine.desktop[30468]:     inhibitor.set(inhibit_screen)
apr 01 13:30:58 thinkpad-t480 caffeine.desktop[30468]:   File "/usr/lib/python3.9/site-packages/caffeine/inhibitors.py", line 46, in set
apr 01 13:30:58 thinkpad-t480 caffeine.desktop[30468]:     self.uninhibit()
apr 01 13:30:58 thinkpad-t480 caffeine.desktop[30468]:   File "/usr/lib/python3.9/site-packages/caffeine/inhibitors.py", line 83, in uninhibit
apr 01 13:30:58 thinkpad-t480 caffeine.desktop[30468]:     self.__proxy.Uninhibit(self.__cookie)
apr 01 13:30:58 thinkpad-t480 caffeine.desktop[30468]:   File "/usr/lib/python3.9/site-packages/dbus/proxies.py", line 141, in __call__
apr 01 13:30:58 thinkpad-t480 caffeine.desktop[30468]:     return self._connection.call_blocking(self._named_service,
apr 01 13:30:58 thinkpad-t480 caffeine.desktop[30468]:   File "/usr/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
apr 01 13:30:58 thinkpad-t480 caffeine.desktop[30468]:     reply_message = self.send_message_with_reply_and_block(
apr 01 13:30:58 thinkpad-t480 caffeine.desktop[30468]: dbus.exceptions.DBusException: org.gnome.SessionManager.GeneralError: Unable to uninhibit: Invalid cookie
```

distro: Manjaro Linux
DE: GNOME 40 on Wayland

**Comment by WhyNotHugo** [comment]
It seems to be happening for all `Inhibitor`s.

@smartlitchi What desktop and screen locker are you using?

**Comment by smartlitchi** [comment]
I use i3wm and got `xset s off dpms 300` setup with i3lock

**Comment by VoodaGod** [comment]
@smartlitchi can you try PR #65

**Comment by WhyNotHugo** [comment]
#65 has been merged as a workaround, please report back if you still have those issues with the latest git version.

I'm leaving this open to further investigate this though, since that's just a workaround.

**Comment by WhyNotHugo** [comment]
This project has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/61
