### ISSUE TITLE
Caffeine occasionally gets stuck inhibiting

### ISSUE THREAD

**Issue by protist** [caffeine-ng/caffeine-ng#67]
After running caffeine for several hours, it seems to get stuck inhibiting, even if there are no relevant processes active. I get the following in the terminal around the same time.

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/caffeine/core.py", line 116, in __attempt_autoactivation
    if window and self._ewmh.getWmState(window):
  File "/usr/lib/python3.9/site-packages/ewmh/ewmh.py", line 373, in getWmState
    states = self._getProperty('_NET_WM_STATE', win) or []
  File "/usr/lib/python3.9/site-packages/ewmh/ewmh.py", line 405, in _getProperty
    atom = win.get_full_property(self.display.get_atom(_type),
  File "/usr/lib/python3.9/site-packages/Xlib/xobject/drawable.py", line 472, in get_full_property
    prop = self.get_property(property, property_type, 0, sizehint)
  File "/usr/lib/python3.9/site-packages/Xlib/xobject/drawable.py", line 455, in get_property
    r = request.GetProperty(display = self.display,
  File "/usr/lib/python3.9/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/usr/lib/python3.9/site-packages/Xlib/protocol/rq.py", line 1389, in reply
    raise self._error
Xlib.error.BadWindow: <class 'Xlib.error.BadWindow'>: code = 3, resource_id = <Resource 0x09c00003>, sequence_number = 21847, major_opcode = 20, minor_opcode = 0
```

Caffeine is otherwise responsive to clicks, and gives no indication of not functioning, except for displaying the "hot coffee" icon and inhibiting when inappropriate. If I quit caffeine and immediately restart it, it no longer inhibits.

caffeine 3.5.1
python 3.9.5
Up-to-date Arch Linux

**Comment by WhyNotHugo** [comment]
This project has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/67
