### ISSUE TITLE
Python update

### ISSUE THREAD

**Issue by zluca** [caffeine-ng/caffeine-ng#8]
Yesterday after last Arch linux update (a lot of python packages updated) caffeine stop working. Im using testing repository by the way, but soon this new packages should hit main repositories.

```
Traceback (most recent call last):
  File "/usr/bin/caffeine", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'caffeine-ng==3.4.2' distribution was not found and is required by the application
```

**Comment by zluca** [comment]
If someone interested i fix it by coping **ewmh** package from /usr/lib/python3.6 to /usr/lib/python3.7

**Comment by WhyNotHugo** [comment]
You need to update or rebuild any python packages that were built using python3.6.

You can get a list via `pacman  -Qoq /usr/lib/python3.6`.
