### ISSUE TITLE
'Namespace AppIndicator3 not available' when executing binary in Fedora 35

### ISSUE THREAD

**Issue by thisisgil** [caffeine-ng/caffeine-ng#92]
[gil@DESKTOP-A5UR4DS bin]$ ./caffeine
Traceback (most recent call last):
  File "/usr/local/bin/./caffeine", line 33, in <module>
    sys.exit(load_entry_point('caffeine-ng==3.5.1.post71+g77611ac', 'gui_scripts', 'caffeine')())
  File "/usr/local/bin/./caffeine", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/site-packages/caffeine_ng-3.5.1.post71+g77611ac-py3.10.egg/caffeine/cli.py", line 9, in <module>
    from caffeine.main import GUI
  File "/usr/local/lib/python3.10/site-packages/caffeine_ng-3.5.1.post71+g77611ac-py3.10.egg/caffeine/main.py", line 29, in <module>
    gi.require_version("AppIndicator3", "0.1")
  File "/usr/lib64/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

**Comment by WhyNotHugo** [comment]
I think you're missing a dependency. Do you have `libappindicator` installed?

**Comment by thisisgil** [comment]
> I think you're missing a dependency. Do you have `libappindicator` installed?

Good spot. I had already checked for libappindicator, but turns out I needed to grab libappindicator-gtk3 from the repos.

It runs now, but I don't have any visibility / icon etc... I'm guessing this is a Gnome 4 thing?

**Comment by MichaelTrip** [comment]
> > I think you're missing a dependency. Do you have `libappindicator` installed?
> 
> Good spot. I had already checked for libappindicator, but turns out I needed to grab libappindicator-gtk3 from the repos.
> 
> It runs now, but I don't have any visibility / icon etc... I'm guessing this is a Gnome 4 thing?

I can confirm i have the same problem. No indicator in i3 on Fedora 35.

**Comment by WhyNotHugo** [comment]
How exactly are you installing? pip? dnf? pipsi?

**Comment by WhyNotHugo** [comment]
This project has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/92
