### ISSUE TITLE
Caffeine breaks on Arch Linux

### ISSUE THREAD

**Issue by epixinvites** [caffeine-ng/caffeine-ng#93]
```
$ caffeine
Traceback (most recent call last):
  File "/usr/bin/caffeine", line 33, in <module>
    sys.exit(load_entry_point('caffeine-ng==3.5.1', 'gui_scripts', 'caffeine')())
  File "/usr/bin/caffeine", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for caffeine-ng
$ sudo pacman -Q caffeine-ng
caffeine-ng 3.5.1-2
```

**Comment by epixinvites** [comment]
Solved by reinstalling it from the AUR.
